'("general","seed")'          : [42]
'("optimizer","config","lr")' : [0.000001, 0.000005, 0.00001, 0.00005, 0.0001, 0.0005, 0.001, 0.002, 0.003, 0.004]
'("model",0,"conformer","size")' : ["small", "medium", "large"]
